# Form implementation generated from reading ui file 'c:\Users\user\Documents\GitHub\PY_Data_Generator\ui\tela.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName("Principal")
        Principal.resize(493, 236)
        Principal.setStyleSheet("")
        self.bt_pessoa = QtWidgets.QPushButton(Principal)
        self.bt_pessoa.setGeometry(QtCore.QRect(10, 60, 151, 41))
        self.bt_pessoa.setObjectName("bt_pessoa")
        self.bt_endereco = QtWidgets.QPushButton(Principal)
        self.bt_endereco.setGeometry(QtCore.QRect(10, 110, 151, 41))
        self.bt_endereco.setObjectName("bt_endereco")
        self.bt_telefone = QtWidgets.QPushButton(Principal)
        self.bt_telefone.setGeometry(QtCore.QRect(10, 160, 151, 41))
        self.bt_telefone.setObjectName("bt_telefone")
        self.label = QtWidgets.QLabel(Principal)
        self.label.setGeometry(QtCore.QRect(20, 10, 461, 41))
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.bt_sair = QtWidgets.QPushButton(Principal)
        self.bt_sair.setGeometry(QtCore.QRect(384, 192, 101, 41))
        self.bt_sair.setObjectName("bt_sair")

        self.retranslateUi(Principal)
        QtCore.QMetaObject.connectSlotsByName(Principal)

    def retranslateUi(self, Principal):
        _translate = QtCore.QCoreApplication.translate
        Principal.setWindowTitle(_translate("Principal", "Form"))
        self.bt_pessoa.setText(_translate("Principal", "Pessoa"))
        self.bt_endereco.setText(_translate("Principal", "Endereço"))
        self.bt_telefone.setText(_translate("Principal", "Telefone"))
        self.label.setText(_translate("Principal", "Gerador de Dados"))
        self.bt_sair.setText(_translate("Principal", "Sair"))
